/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
        main()init_dist(args.launcher, **cfg.dist_params)

  File "tools/train.py", line 168, in main
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
        torch.cuda.set_device(rank % num_gpus)init_dist(args.launcher, **cfg.dist_params)

ZeroDivisionError  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
: integer division or modulo by zero
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 168, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 203036) of binary: /hpc2hdd/home/jpan305/miniconda3/envs/openocc/bin/python
Traceback (most recent call last):
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/hpc2hdd/home/jpan305/miniconda3/envs/openocc/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 203037)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 203038)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 203039)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 203040)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 203041)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 203042)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 203043)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-06_21:12:00
  host      : gpu3-9.hkust-gz.edu.cn
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 203036)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
